/**
 * Render a bundle of rules into a single markdown file (e.g. CLAUDE.md, AGENTS.md).
 *
 * @param {string} title - File title (e.g. "CLAUDE.md")
 * @param {Array<{ rel: string, content: string }>} bundle - Array of { rel, content }
 * @returns {string} - Rendered markdown
 */

export function renderBundleMd(
  title: string,
  bundle: { rel: string; content: string }[],
) {
  const header = `# ${title}

This file is auto-generated by \`pnpm rules:compile\`.
Do not edit manually. Edit files in \`/rules\` and recompile.

## Project Rules

`
  const sections = bundle.map(
    (item) => `## ${item.rel}

\`\`\`mdc
${item.content}
\`\`\``,
  )
  return header + sections.join('\n\n') + '\n'
}
