import path from 'node:path'

/**
 * Render a bundle into a single markdown file with per-rule mdc blocks and frontmatter.
 * Used for GEMINI.md and WINDSURF.md.
 *
 * @param {string} title - File title (e.g. "GEMINI.md")
 * @param {string} subtitle - Section subtitle after "Project Rules" (e.g. "" or "(Windsurf/Cascade)")
 * @param {Array<{ rel: string, frontmatter: object, content: string }>} bundle - From generateBundle
 * @param {(item: { frontmatter: object }) => Record<string, string>} getExtraFrontmatter - Extra keys (e.g. activation, priority)
 * @returns {string} - Rendered markdown
 */

export function renderBundleWithMdcFrontmatter(
  title: string,
  subtitle: string,
  bundle: {
    rel: string
    frontmatter: Record<string, unknown>
    content: string
  }[],
  getExtraFrontmatter: (item: {
    rel: string
    frontmatter: Record<string, unknown>
    content: string
  }) => Record<string, string>,
) {
  const header = `# ${title}

This file is auto-generated by \`pnpm rules:compile\`.
Do not edit manually. Edit files in \`/rules\` and recompile.

## Project Rules${subtitle ? ` ${subtitle}` : ''}

`
  const sections = bundle.map((item) => {
    const { rel, frontmatter, content } = item
    const normalizedRel = rel.split(path.sep).join('/')
    const titleLine =
      typeof frontmatter.description === 'string'
        ? frontmatter.description
        : rel
    const extra = getExtraFrontmatter(item)
    const extraLines = Object.entries(extra)
      .map(([k, v]) => `${k}: "${v}"`)
      .join('\n')

    const globs =
      typeof frontmatter.globs === 'string' ? frontmatter.globs : '*'
    const alwaysApply =
      typeof frontmatter.alwaysApply === 'boolean'
        ? String(frontmatter.alwaysApply)
        : 'false'

    return `## ${normalizedRel}

\`\`\`mdc
---
description: "${titleLine}"
globs: "${globs}"
alwaysApply: ${alwaysApply}
${extraLines ? extraLines + '\n' : ''}---

${content.trim()}
\`\`\`
`
  })
  return header + sections.join('\n')
}
