export const GLOBAL_INSTRUCTIONS = [
  '## Identity / Emails',
  '',
  '- `cristian@favish.com` is the work email. Use it only for Favish-related projects.',
  '- `info@busirocket.com` is the personal/side-project email. Use it for personal projects, test recipients, account lookups, and side-project work.',
  '- When the project context is unclear, ask before using either email.',
  '',
  '## Git Commits (hard rule, no exceptions)',
  '',
  '- Never add assistant, model, vendor, or tool attribution footers (e.g. `Co-Authored-By`, `Generated with`).',
  '- Never reference an assistant, model, or AI tool in commit messages, PR titles, or PR descriptions.',
  '- Write commit messages as if the human author wrote them. Use the existing `user.name` and `user.email` from git config.',
  '- This rule applies even if the user does not mention it. Do not ask, do not opt-in, do not negotiate.',
  '',
  '## Written Artifacts',
  '',
  '- All code, comments, identifiers, docs, commit messages, PR titles/descriptions, and generated artifacts must be written in English.',
  '- The only exception is when the user explicitly requests another language for a specific artifact.',
  "- Chat replies may use the user's language.",
  '',
  '## Memory',
  '',
  '- Before asking about previously established project conventions, deployment details, credentials locations, CI behavior, or past decisions, check memory first.',
  '- Prefer `mempalace search "<topic>" --wing <project>` for targeted recall.',
  '- Save only high-signal memory: decisions, gotchas, feedback, bugs, and runbooks.',
  '- Do not use the mempalace knowledge graph path; semantic search is the retrieval path.',
  '- Use one canonical wing per project: the repo folder basename, normalized by mempalace.',
  '',
  '## Current Documentation',
  '',
  '- When working with libraries, frameworks, SDKs, CLIs, cloud services, or APIs, fetch current docs before relying on memory.',
  '- Prefer the Context7 MCP server for package, framework, and API documentation.',
  "- Resolve the library first, then query the selected library docs with the user's concrete task.",
  '',
]
